
#How to edit this file: http://guides.cocoapods.org/using/the-podfile.html
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://git.coding.net/CocoaPods/Specs.git'
target "learnGPUImage" do

platform :ios, "8.0"

pod 'GPUImage'

inhibit_all_warnings!

end
